#load "Domain.fs"
#load "CustomBlocks.fs"

open System
open System.IO
open YamlDotNet.Serialization
open CustomBlocks

// Test the exact YAML format being generated by buildAlbums
let testYaml = """- media_type: image
  uri: /images/fall-mountains/sunrise.jpg
  alt_text: Sunrise over mountains in fall
  caption: Beautiful autumn sunrise scene
  aspect: ""
- media_type: image
  uri: /images/fall-mountains/sunset.jpg
  alt_text: Sunset over mountains in fall
  caption: Peaceful autumn sunset view
  aspect: """"

printfn "Testing YAML format:"
printfn "%s" testYaml
printfn ""

try
    let deserializer = DeserializerBuilder().Build()
    let mediaItems = deserializer.Deserialize<MediaItem array>(testYaml)
    printfn "Success! Parsed %d items:" mediaItems.Length
    for i, item in Array.indexed mediaItems do
        printfn "  Item %d: %s -> %s" i item.media_type item.uri
with
| ex -> 
    printfn "Error: %s" ex.Message
