open System
open YamlDotNet.Serialization

// Simple MediaItem type for testing
type TestMediaItem = {
    media_type: string
    uri: string
    alt_text: string
    caption: string
    aspect: string
}

// Test the exact YAML format being generated by buildAlbums
let testYaml = "- media_type: image\n  uri: /images/fall-mountains/sunrise.jpg\n  alt_text: Sunrise over mountains in fall\n  caption: Beautiful autumn sunrise scene\n  aspect: \"\"\n- media_type: image\n  uri: /images/fall-mountains/sunset.jpg\n  alt_text: Sunset over mountains in fall\n  caption: Peaceful autumn sunset view\n  aspect: \"\""

printfn "Testing YAML format:"
printfn "%s" testYaml
printfn ""

try
    let deserializer = DeserializerBuilder().Build()
    let mediaItems = deserializer.Deserialize<TestMediaItem array>(testYaml)
    printfn "Success - Parsed %d items" mediaItems.Length
    for i, item in Array.indexed mediaItems do
        printfn "  Item %d: %s -> %s" i item.media_type item.uri
with
| ex -> 
    printfn "Error: %s" ex.Message
