name: 🔖 Post a Bookmark
description: Create a new bookmark post for the website
title: "[Bookmark] "
labels: ["bookmark"]
body:
  - type: markdown
    attributes:
      value: |
        ## Create a New Bookmark Post
        
        Use this form to create a bookmark post that will automatically generate a pull request with a properly formatted markdown file.
        
        **Note**: This will create a new bookmark post in the `_src/bookmarks/` directory and generate a PR for review.

  - type: input
    id: target_url
    attributes:
      label: Target URL
      description: The URL you are bookmarking
      placeholder: "https://example.com/some-resource"
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: Title
      description: The title of your bookmark post
      placeholder: "e.g., Great resource for web development"
    validations:
      required: true

  - type: textarea
    id: content
    attributes:
      label: Content (Optional)
      description: Your bookmark description or notes (supports Markdown). Leave blank for simple bookmarks.
      placeholder: |
        Write your bookmark description here. You can use Markdown formatting.
        
        - Lists are supported
        - **Bold** and *italic* text
        - [Links](https://example.com)
        - Code blocks and other Markdown features
        
        Note: You can leave this blank for simple bookmarks without additional commentary.
    validations:
      required: false

  - type: input
    id: slug
    attributes:
      label: Slug (Optional)
      description: Custom URL slug for your bookmark. If not provided, one will be generated from the title.
      placeholder: "e.g., my-custom-slug (leave blank to auto-generate)"
    validations:
      required: false

  - type: input
    id: tags
    attributes:
      label: Tags (Optional)
      description: Comma-separated tags for categorizing your bookmark
      placeholder: "e.g., webdev, tools, resources"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        
        **What happens next?**
        
        1. 🤖 A GitHub Action will process this issue
        2. 📄 Generate a properly formatted markdown file in `_src/bookmarks/`
        3. 🔀 Create a pull request with your content
        4. ✅ The issue will be closed automatically
        5. 🚀 After PR review and merge, your bookmark will be live on the website
        
        The generated content will include proper frontmatter with bookmark type, target URL, publication date, and tags.