name: 📷 Post Media
description: Create a new media post (image, video, audio) for the website
title: "[Media] "
labels: ["media"]
body:
  - type: markdown
    attributes:
      value: |
        ## Create a New Media Post
        
        Use this form to create a media post that will automatically generate a pull request with a properly formatted markdown file.
        
        **Note**: This will create a new media post in the `_src/media/` directory and generate a PR for review.

  - type: dropdown
    id: media_type
    attributes:
      label: Media Type
      description: Select the type of media you are posting
      options:
        - image
        - video
        - audio
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: Title
      description: The title of your media post
      placeholder: "e.g., Beautiful sunset at the beach"
    validations:
      required: true

  - type: textarea
    id: attachment
    attributes:
      label: Attachment(s)
      description: Attach your media file(s) here. After uploading, copy the URL(s) that GitHub generates. For multiple files, put each URL on a new line.
      placeholder: |
        1. Click the attachment area below
        2. Upload your media file(s) (image, video, or audio)
        3. GitHub will generate URLs like: https://github.com/user/repo/assets/...
        4. Copy those URLs and paste them here (one per line for multiple files)
        
        Single file example:
        https://github.com/lqdev/luisquintanilla.me/assets/11130940/example-file.jpg
        
        Multiple files example:
        https://github.com/lqdev/luisquintanilla.me/assets/11130940/image1.jpg
        https://github.com/lqdev/luisquintanilla.me/assets/11130940/image2.jpg
    validations:
      required: true

  - type: textarea
    id: content
    attributes:
      label: Content (Optional)
      description: Additional content or description for your media post (supports Markdown). This will appear above the media.
      placeholder: |
        Write your media post content here. You can use Markdown formatting.
        
        - Lists are supported
        - **Bold** and *italic* text
        - [Links](https://example.com)
        - Code blocks and other Markdown features
        
        Note: You can leave this blank for media-only posts.
    validations:
      required: false

  - type: input
    id: caption
    attributes:
      label: Caption (Optional)
      description: A caption or description for your media (appears in the media block)
      placeholder: "e.g., Enjoying the golden hour at the beach"
    validations:
      required: false

  - type: dropdown
    id: orientation
    attributes:
      label: Orientation (Optional)
      description: The aspect ratio/orientation of your media (for display purposes)
      options:
        - landscape
        - portrait
    validations:
      required: false

  - type: input
    id: slug
    attributes:
      label: Slug (Optional)
      description: Custom URL slug for your media post. If not provided, one will be generated from the title.
      placeholder: "e.g., my-custom-slug (leave blank to auto-generate)"
    validations:
      required: false

  - type: input
    id: tags
    attributes:
      label: Tags (Optional)
      description: Comma-separated tags for categorizing your media
      placeholder: "e.g., photography, nature, travel"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        
        **What happens next?**
        
        1. 🤖 A GitHub Action will process this issue
        2. 📄 Generate a properly formatted markdown file in `_src/media/`
        3. 🔀 Create a pull request with your content
        4. ✅ The issue will be closed automatically
        5. 🚀 After PR review and merge, your media will be live on the website
        
        The generated content will include proper frontmatter with media type, publication date, and a custom :::media::: block for your attachment.