name: 📷 Post Media
description: Create a new media post (image, video, audio) for the website
title: "[Media] "
labels: ["media"]
body:
  - type: markdown
    attributes:
      value: |
        ## Create a New Media Post
        
        Use this form to create a media post that will automatically generate a pull request with a properly formatted markdown file.
        
        **Note**: This will create a new media post in the `_src/media/` directory and generate a PR for review.
        
        **Media Type Detection**: The system will automatically detect media types (image, video, audio) based on file extensions and content patterns. You can mix different media types in the same post.

  - type: input
    id: post_title
    attributes:
      label: Title
      description: The title of your media post
      placeholder: "e.g., Beautiful sunset at the beach"
    validations:
      required: true

  - type: textarea
    id: content
    attributes:
      label: Content and Attachments
      description: Write your media post content here. You can drag and drop images, videos, or audio files directly into this field. GitHub will automatically generate markdown for attachments.
      placeholder: |
        Write your media post content here. You can use Markdown formatting.
        
        - Drag and drop media files directly into this field
        - GitHub will automatically create ![filename](URL) markdown for attachments
        - You can add text, lists, links, and other markdown content
        - **Bold** and *italic* text are supported
        - [Links](https://example.com) work normally
        
        Example with attachments:
        Here's my latest photo from the trip:
        
        ![Beautiful sunset](https://github.com/user/repo/assets/12345/sunset.jpg)
        
        And here's a video of the waves:
        
        ![Ocean waves video](https://github.com/user/repo/assets/12345/waves.mp4)
    validations:
      required: true

  - type: dropdown
    id: orientation
    attributes:
      label: Orientation (Optional)
      description: The aspect ratio/orientation of your media (for display purposes)
      options:
        - landscape
        - portrait
    validations:
      required: false

  - type: input
    id: slug
    attributes:
      label: Slug (Optional)
      description: Custom URL slug for your media post. If not provided, one will be generated from the title.
      placeholder: "e.g., my-custom-slug (leave blank to auto-generate)"
    validations:
      required: false

  - type: input
    id: tags
    attributes:
      label: Tags (Optional)
      description: Comma-separated tags for categorizing your media
      placeholder: "e.g., photography, nature, travel"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        
        **What happens next?**
        
        1. 🤖 A GitHub Action will process this issue
        2. 📄 Generate a properly formatted markdown file in `_src/media/`
        3. 🔀 Create a pull request with your content
        4. ✅ The issue will be closed automatically
        5. 🚀 After PR review and merge, your media will be live on the website
        
        The generated content will include proper frontmatter with media type, publication date, and a custom :::media::: block for your attachment.