/**
 * Avatar Flip Card
 * --------------------------------------------------------------------------
 * Adds card-flip behavior to any element with `[data-avatar-flip]`. Clicking,
 * tapping, or activating the element with the keyboard flips it horizontally
 * to reveal a programmatically generated QR code that points at the URL given
 * by `data-flip-url` (e.g. "/" for the homepage).
 *
 * The QR code is generated lazily on the first flip using the same
 * `qr-code-styling` library and the same visual options used by the QR modal
 * in `qrcode.js`, so the QR side looks consistent with QR codes elsewhere on
 * the site (rounded slate dots, accent-color corners, white background, with
 * the avatar embedded in the center).
 *
 * Maintenance notes for future contributors:
 *   - Markup is generated by `avatarFlipCard` in `Views/LayoutViews.fs`.
 *   - 3D-flip styles live in `_src/css/custom/timeline.css`
 *     (`.avatar-flip-card`, `.avatar-flip-inner`, `.avatar-flip-front`,
 *      `.avatar-flip-back`, `.avatar-flip-qr`, `.avatar-flip-sr-only`).
 *   - The `qr-code-styling` library is loaded from CDN in `Views/Layouts.fs`.
 *   - This script is purely additive: if it (or the library) fails to load,
 *     the avatar still renders normally as the front face of the card.
 *
 * Accessibility:
 *   - The host element is `role="button"`, focusable, and toggles `aria-pressed`.
 *   - Enter and Space activate the flip; Escape flips back and restores focus.
 *   - The back face is `aria-hidden` until flipped so screen readers don't
 *     announce a hidden QR code.
 */
(function () {
    'use strict';

    // QR styling kept in sync with `_src/js/qrcode.js` so the avatar-flip QR
    // matches QR codes elsewhere on the site. Smaller dimensions because the
    // QR has to fit inside the avatar's circular footprint.
    var QR_OPTIONS = {
        width: 140,
        height: 140,
        dotsOptions: { color: '#1a2332', type: 'rounded' },
        cornersSquareOptions: { color: '#ff6b35', type: 'extra-rounded' },
        cornersDotOptions: { color: '#ff6b35' },
        backgroundOptions: { color: '#ffffff' },
        imageOptions: { crossOrigin: 'anonymous', margin: 2, imageSize: 0.25 }
    };

    // Resolve the avatar image URL with a graceful fallback so the QR center
    // image never blocks generation if `/avatar.png` is unavailable.
    function loadAvatarImage() {
        return new Promise(function (resolve) {
            var img = new Image();
            img.crossOrigin = 'anonymous';
            img.onload = function () { resolve('/avatar.png'); };
            img.onerror = function () { resolve(null); }; // QR generates without a center image
            img.src = '/avatar.png';
        });
    }

    function AvatarFlip(element) {
        this.el = element;
        this.url = element.getAttribute('data-flip-url') || '/';
        this.frontEl = element.querySelector('.avatar-flip-front');
        this.backEl = element.querySelector('.avatar-flip-back');
        this.qrTarget = element.querySelector('[data-qr-target]');
        this.qrBuilt = false;
        this.qrInstance = null;
        this.attach();
    }

    AvatarFlip.prototype.isFlipped = function () {
        return this.el.classList.contains('is-flipped');
    };

    AvatarFlip.prototype.toggle = function () {
        if (this.isFlipped()) {
            this.flipBack();
        } else {
            this.flipForward();
        }
    };

    AvatarFlip.prototype.flipForward = function () {
        var self = this;
        // Kick off QR generation before flipping so the back face has content
        // ready (or close to ready) by the time the animation lands.
        this.ensureQR().catch(function (err) {
            // Surface only — never block the flip on a QR generation failure.
            console.warn('Avatar flip: QR generation failed', err);
        });
        this.el.classList.add('is-flipped');
        this.el.setAttribute('aria-pressed', 'true');
        if (this.frontEl) this.frontEl.setAttribute('aria-hidden', 'true');
        if (this.backEl) this.backEl.setAttribute('aria-hidden', 'false');

        // Defer registering the outside listener until after this click bubbles
        // up; otherwise the originating click would immediately flip back.
        if (!this._outsideHandlerActive) {
            setTimeout(function () { self._outsideHandlerActive = true; }, 0);
        }
    };

    AvatarFlip.prototype.flipBack = function () {
        this.el.classList.remove('is-flipped');
        this.el.setAttribute('aria-pressed', 'false');
        if (this.frontEl) this.frontEl.setAttribute('aria-hidden', 'false');
        if (this.backEl) this.backEl.setAttribute('aria-hidden', 'true');
        this._outsideHandlerActive = false;
    };

    AvatarFlip.prototype.ensureQR = function () {
        var self = this;
        if (this.qrBuilt || !this.qrTarget) return Promise.resolve();

        // Library missing: render a plain accessible link so the back face is
        // still meaningful. The card-flip itself still works.
        if (typeof QRCodeStyling === 'undefined') {
            this.qrBuilt = true;
            this.qrTarget.innerHTML = '';
            var link = document.createElement('a');
            link.href = this.url;
            link.className = 'avatar-flip-fallback-link';
            link.textContent = 'Visit homepage';
            this.qrTarget.appendChild(link);
            return Promise.resolve();
        }

        // Resolve to absolute so scanned QR codes always work regardless of
        // the page they were rendered on.
        var absoluteUrl;
        try {
            absoluteUrl = new URL(this.url, window.location.origin).href;
        } catch (e) {
            absoluteUrl = this.url;
        }

        return loadAvatarImage().then(function (avatarSrc) {
            var options = Object.assign({}, QR_OPTIONS, { data: absoluteUrl });
            if (avatarSrc) options.image = avatarSrc;
            self.qrInstance = new QRCodeStyling(options);
            self.qrTarget.innerHTML = '';
            self.qrInstance.append(self.qrTarget);
            self.qrBuilt = true;
        });
    };

    AvatarFlip.prototype.attach = function () {
        var self = this;

        // Pointer activation — works for mouse and touch (touch fires click).
        this.el.addEventListener('click', function (e) {
            // Stop propagation so the document-level outside handler doesn't
            // immediately reverse what we just did.
            e.stopPropagation();
            self.toggle();
        });

        // Keyboard activation. Enter/Space toggle, Escape always flips back.
        this.el.addEventListener('keydown', function (e) {
            if (e.key === 'Enter' || e.key === ' ' || e.key === 'Spacebar') {
                e.preventDefault();
                self.toggle();
            } else if (e.key === 'Escape' && self.isFlipped()) {
                e.preventDefault();
                self.flipBack();
            }
        });

        // Click / tap outside the card flips it back. Cheap early-exit when
        // the card isn't flipped keeps this listener effectively free.
        document.addEventListener('click', function (e) {
            if (!self._outsideHandlerActive || !self.isFlipped()) return;
            if (!self.el.contains(e.target)) {
                self.flipBack();
            }
        });

        // Same idea for touch devices that synthesize click after touchend —
        // covered by the click listener above. We keep `touchstart` only as a
        // safety net for stacked overlays that may swallow the click.
        document.addEventListener('touchstart', function (e) {
            if (!self._outsideHandlerActive || !self.isFlipped()) return;
            if (!self.el.contains(e.target)) {
                self.flipBack();
            }
        }, { passive: true });
    };

    function init() {
        var nodes = document.querySelectorAll('[data-avatar-flip]');
        for (var i = 0; i < nodes.length; i++) {
            // Guard against double-initialization if this script ever loads twice.
            if (nodes[i].__avatarFlip) continue;
            nodes[i].__avatarFlip = new AvatarFlip(nodes[i]);
        }
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
})();
