name: Publish Website
on: push
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [master]
jobs:
  Build-Website:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZCRED }}
      - name: Setup .NET SDK 5.x
        uses: actions/setup-dotnet@v1.7.2
        with: 
          dotnet-version: '5.0.x'
      - name: Install Dependencies
        run: dotnet restore
      - name: Build website
        run: dotnet build --no-restore
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
              az storage blob upload-batch --account-name ${{secrets.STORAGE_ACC_NAME}} -d '$web' -s ./_public
      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name ${{secrets.CDN_PROFILE_NAME}} --name ${{secrets.CDN_ENDPOINT_NAME}} --resource-group ${{secrets.RG}}

    # Azure logout 
      - name: logout
        run: |
              az logout        


