name: Publish Website
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [master]
jobs:
  Build-Website:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZCRED }}
      - name: Setup .NET SDK 5.x
        uses: actions/setup-dotnet@v1.7.2
        with: 
          dotnet-version: '5.0.x'
      - name: Install Dependencies
        run: dotnet restore
      - name: Build website
        run: dotnet build --no-restore


