name: Publish Website
on:
  push:
    branches: [ main ]
  workflow_dispatch:     
  # pull_request:
  #   branches: [ main ]
jobs:
  Build-Website:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZCRED }}
      - name: Setup .NET SDK 9.x
        uses: actions/setup-dotnet@v1.9.0
        with: 
          dotnet-version: '9.0.x'
      - name: Install Dependencies
        run: dotnet restore
      - name: Build project
        run: dotnet build --no-restore
      - name: Generate website
        run: dotnet run
      - name: Check total webpage size
        run: du -sh ./_public
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.69.0
          # azcopy workadound https://github.com/Azure/azure-cli/issues/30635
          inlineScript: |
              az storage blob sync --account-name ${{secrets.STORAGE_ACC_NAME}} -c '$web' -s ./_public
      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          azcliversion: 2.67.0
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name ${{secrets.CDN_PROFILE_NAME}} --name ${{secrets.CDN_ENDPOINT_NAME}} --resource-group ${{secrets.RG}}
      - name: Send Webmentions
        run: dotnet fsi Scripts/send-webmentions.fsx

    # Azure logout 
      - name: logout
        run: |
              az logout        


