name: Publish Website
on: [push]
jobs:
  Build-Website:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK 5.x
        uses: actions/setup-dotnet@v2
        with: 
          dotnet-version: '5.0.x'
      - name: Install Dependencies
        run: dotnet restore
      - name: Build website
        run: dotnet build --no-restore


