name: Publish Website
on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]
jobs:
  Build-Website:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZCRED }}
      - name: Setup .NET SDK 6.x
        uses: actions/setup-dotnet@v1.9.0
        with: 
          dotnet-version: '6.0.x'
      - name: Install Dependencies
        run: dotnet restore
      - name: Build project
        run: dotnet build --no-restore
      - name: Generate website
        run: dotnet run
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
              az storage blob upload-batch --account-name ${{secrets.STORAGE_ACC_NAME}} -d '$web' -s ./_public
      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name ${{secrets.CDN_PROFILE_NAME}} --name ${{secrets.CDN_ENDPOINT_NAME}} --resource-group ${{secrets.RG}}

    # Azure logout 
      - name: logout
        run: |
              az logout        


